// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleAPI.Context;

namespace VehicleAPI.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20220711043234_FirstMigrationToDb")]
    partial class FirstMigrationToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleAPI.Models.Vehicle", b =>
                {
                    b.Property<string>("RegistrationNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AcAvailable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeat")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegistrationNo");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            RegistrationNo = "AP02CD0202",
                            AcAvailable = "No",
                            ModelName = "Chevrolet Tavera",
                            NumberOfSeat = 9,
                            VehicleType = "SUV"
                        },
                        new
                        {
                            RegistrationNo = "KL03EF0303",
                            AcAvailable = "Yes",
                            ModelName = "Chevrolet Enjoy",
                            NumberOfSeat = 7,
                            VehicleType = "SUV"
                        },
                        new
                        {
                            RegistrationNo = "KA04GH0404",
                            AcAvailable = "Yes",
                            ModelName = "Mahindra Tourister",
                            NumberOfSeat = 15,
                            VehicleType = "Van"
                        },
                        new
                        {
                            RegistrationNo = "TN01AB0202",
                            AcAvailable = "Yes",
                            ModelName = "Chevrolet Tavera",
                            NumberOfSeat = 9,
                            VehicleType = "SUV"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
